"""Public package facade for Document KV Cache.

This facade exposes the document-generic import path and console script targets
used by Cachet. The former restaurant-specific compatibility package is no
longer consulted for root exports or attribute fallback.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any


_PUBLIC_SUBMODULES = frozenset(
    {
        "admission",
        "adapter_scaffold",
        "benchmark_plan",
        "benchmark_plan_executor",
        "benchmark_handoff_bundles",
        "benchmark_handoffs",
        "benchmark_runner",
        "benchmarks",
        "cache",
        "databricks_engine_probe_job",
        "databricks_job",
        "databricks_runs",
        "databricks_sglang_smoke_job",
        "databricks_storage_benchmark_job",
        "databricks_vllm_smoke_job",
        "dataset_prep",
        "engine",
        "engine_adapters",
        "engine_launch_config",
        "engine_probe",
        "engine_protocol",
        "github_governance",
        "kvpack",
        "legacy_compatibility",
        "live_server",
        "manifest",
        "materializer",
        "model_profiles",
        "models",
        "native_probe_factories",
        "openai_compatible",
        "planner",
        "probe_fixtures",
        "pr_evidence",
        "release_bundle",
        "release_evidence",
        "repository_hygiene",
        "service",
        "serving_env",
        "sglang_runtime_preflight",
        "sglang_smoke",
        "storage",
        "storage_benchmark",
        "template_resources",
        "transformers_generator",
        "vllm_runtime_contract_data",
        "vllm_runtime_preflight",
        "vllm_smoke",
        "workflow",
    }
)
_DOCUMENT_ROOT_EXPORTS = {
    'AdmissionQueue': ('document_kv_cache.admission', 'AdmissionQueue'),
    'PreparedRequest': ('document_kv_cache.admission', 'PreparedRequest'),
    'BenchmarkCommand': ('document_kv_cache.benchmark_plan', 'BenchmarkCommand'),
    'BenchmarkDatasetPath': ('document_kv_cache.benchmark_plan', 'BenchmarkDatasetPath'),
    'BenchmarkJobPlan': ('document_kv_cache.benchmark_plan', 'BenchmarkJobPlan'),
    'BenchmarkPlanConfig': ('document_kv_cache.benchmark_plan', 'BenchmarkPlanConfig'),
    'ENGINE_PROBE_TARGETS_RECORD_TYPE': ('document_kv_cache.benchmark_plan', 'ENGINE_PROBE_TARGETS_RECORD_TYPE'),
    'ENGINE_PROBE_TARGETS_SCHEMA_VERSION': ('document_kv_cache.benchmark_plan', 'ENGINE_PROBE_TARGETS_SCHEMA_VERSION'),
    'EngineProbePlanConfig': ('document_kv_cache.benchmark_plan', 'EngineProbePlanConfig'),
    'PLAN_VERSION': ('document_kv_cache.benchmark_plan', 'PLAN_VERSION'),
    'ReleaseBundlePlanConfig': ('document_kv_cache.benchmark_plan', 'ReleaseBundlePlanConfig'),
    'ReleaseEvidencePlanConfig': ('document_kv_cache.benchmark_plan', 'ReleaseEvidencePlanConfig'),
    'StorageBenchmarkPlanConfig': ('document_kv_cache.benchmark_plan', 'StorageBenchmarkPlanConfig'),
    'benchmark_job_plan_to_record': ('document_kv_cache.benchmark_plan', 'benchmark_job_plan_to_record'),
    'build_v1_benchmark_plan': ('document_kv_cache.benchmark_plan', 'build_v1_benchmark_plan'),
    'engine_probe_targets_to_record': ('document_kv_cache.benchmark_plan', 'engine_probe_targets_to_record'),
    'write_benchmark_job_plan_json': ('document_kv_cache.benchmark_plan', 'write_benchmark_job_plan_json'),
    'write_benchmark_job_plan_shell': ('document_kv_cache.benchmark_plan', 'write_benchmark_job_plan_shell'),
    'write_engine_probe_targets_json': ('document_kv_cache.benchmark_plan', 'write_engine_probe_targets_json'),
    'BenchmarkCommandResult': ('document_kv_cache.benchmark_plan_executor', 'BenchmarkCommandResult'),
    'benchmark_command_results_to_record': ('document_kv_cache.benchmark_plan_executor', 'benchmark_command_results_to_record'),
    'execute_benchmark_job_plan': ('document_kv_cache.benchmark_plan_executor', 'execute_benchmark_job_plan'),
    'execute_benchmark_job_plan_json': ('document_kv_cache.benchmark_plan_executor', 'execute_benchmark_job_plan_json'),
    'write_benchmark_command_results_json': ('document_kv_cache.benchmark_plan_executor', 'write_benchmark_command_results_json'),
    'BENCHMARK_RUN_RECORD_TYPE': ('document_kv_cache.benchmark_runner', 'BENCHMARK_RUN_RECORD_TYPE'),
    'BenchmarkEngine': ('document_kv_cache.benchmark_runner', 'BenchmarkEngine'),
    'BenchmarkEngineRequest': ('document_kv_cache.benchmark_runner', 'BenchmarkEngineRequest'),
    'BenchmarkGeneration': ('document_kv_cache.benchmark_runner', 'BenchmarkGeneration'),
    'BenchmarkRunResult': ('document_kv_cache.benchmark_runner', 'BenchmarkRunResult'),
    'OpenAICompatibleBenchmarkConfig': ('document_kv_cache.benchmark_runner', 'OpenAICompatibleBenchmarkConfig'),
    'benchmark_run_result_to_record': ('document_kv_cache.benchmark_runner', 'benchmark_run_result_to_record'),
    'default_benchmark_arms': ('document_kv_cache.benchmark_runner', 'default_benchmark_arms'),
    'load_benchmark_jsonl': ('document_kv_cache.benchmark_runner', 'load_benchmark_jsonl'),
    'load_v1_jsonl_suite': ('document_kv_cache.benchmark_runner', 'load_v1_jsonl_suite'),
    'run_benchmark_suite': ('document_kv_cache.benchmark_runner', 'run_benchmark_suite'),
    'run_openai_compatible_v1_benchmark': ('document_kv_cache.benchmark_runner', 'run_openai_compatible_v1_benchmark'),
    'write_benchmark_run_result_json': ('document_kv_cache.benchmark_runner', 'write_benchmark_run_result_json'),
    'BASELINE_PREFILL_ARM': ('document_kv_cache.benchmarks', 'BASELINE_PREFILL_ARM'),
    'BenchmarkArm': ('document_kv_cache.benchmarks', 'BenchmarkArm'),
    'BenchmarkComparison': ('document_kv_cache.benchmarks', 'BenchmarkComparison'),
    'BenchmarkDatasetSpec': ('document_kv_cache.benchmarks', 'BenchmarkDatasetSpec'),
    'BenchmarkExample': ('document_kv_cache.benchmarks', 'BenchmarkExample'),
    'BenchmarkPromptParts': ('document_kv_cache.benchmarks', 'BenchmarkPromptParts'),
    'BenchmarkReportRow': ('document_kv_cache.benchmarks', 'BenchmarkReportRow'),
    'BenchmarkSuite': ('document_kv_cache.benchmarks', 'BenchmarkSuite'),
    'CACHE_REUSE_ARM': ('document_kv_cache.benchmarks', 'CACHE_REUSE_ARM'),
    'DEFAULT_HARDWARE_TARGET': ('document_kv_cache.benchmarks', 'DEFAULT_HARDWARE_TARGET'),
    'DEFAULT_V1_MODEL_ID': ('document_kv_cache.benchmarks', 'DEFAULT_V1_MODEL_ID'),
    'InferenceMeasurement': ('document_kv_cache.benchmarks', 'InferenceMeasurement'),
    'LatencySummary': ('document_kv_cache.benchmarks', 'LatencySummary'),
    'SUPPORTED_V1_DATASETS': ('document_kv_cache.benchmarks', 'SUPPORTED_V1_DATASETS'),
    'SUPPORTED_V1_HARDWARE_TARGETS': ('document_kv_cache.benchmarks', 'SUPPORTED_V1_HARDWARE_TARGETS'),
    'V1BenchmarkEvidence': ('document_kv_cache.benchmarks', 'V1BenchmarkEvidence'),
    'answer_found': ('document_kv_cache.benchmarks', 'answer_found'),
    'baseline_prefill_arm': ('document_kv_cache.benchmarks', 'baseline_prefill_arm'),
    'build_cache_prefix_text': ('document_kv_cache.benchmarks', 'build_cache_prefix_text'),
    'build_cache_suffix_text': ('document_kv_cache.benchmarks', 'build_cache_suffix_text'),
    'build_prefill_prompt': ('document_kv_cache.benchmarks', 'build_prefill_prompt'),
    'build_prompt_parts': ('document_kv_cache.benchmarks', 'build_prompt_parts'),
    'compare_to_baseline': ('document_kv_cache.benchmarks', 'compare_to_baseline'),
    'dataset_spec': ('document_kv_cache.benchmarks', 'dataset_spec'),
    'document_kv_cache_arm': ('document_kv_cache.benchmarks', 'document_kv_cache_arm'),
    'evaluate_v1_benchmark_evidence': ('document_kv_cache.benchmarks', 'evaluate_v1_benchmark_evidence'),
    'exact_match': ('document_kv_cache.benchmarks', 'exact_match'),
    'format_document_context': ('document_kv_cache.benchmarks', 'format_document_context'),
    'normalize_answer': ('document_kv_cache.benchmarks', 'normalize_answer'),
    'summarize_measurements': ('document_kv_cache.benchmarks', 'summarize_measurements'),
    'validate_v1_hardware_target': ('document_kv_cache.benchmarks', 'validate_v1_hardware_target'),
    'v1_dataset_specs': ('document_kv_cache.benchmarks', 'v1_dataset_specs'),
    'validate_v1_dataset': ('document_kv_cache.benchmarks', 'validate_v1_dataset'),
    'ByteLRU': ('document_kv_cache.cache', 'ByteLRU'),
    'CacheTier': ('document_kv_cache.cache', 'CacheTier'),
    'ChunkCache': ('document_kv_cache.cache', 'ChunkCache'),
    'ChunkCacheResult': ('document_kv_cache.cache', 'ChunkCacheResult'),
    'ChunkCacheStats': ('document_kv_cache.cache', 'ChunkCacheStats'),
    'DEFAULT_DATABRICKS_ENGINE_PROBE_BACKEND_CONFIG_KEY': ('document_kv_cache.databricks_engine_probe_job', 'DEFAULT_DATABRICKS_ENGINE_PROBE_BACKEND_CONFIG_KEY'),
    'DEFAULT_DATABRICKS_ENGINE_PROBE_PURPOSE': ('document_kv_cache.databricks_engine_probe_job', 'DEFAULT_DATABRICKS_ENGINE_PROBE_PURPOSE'),
    'DEFAULT_DATABRICKS_ENGINE_PROBE_RUN_NAME': ('document_kv_cache.databricks_engine_probe_job', 'DEFAULT_DATABRICKS_ENGINE_PROBE_RUN_NAME'),
    'DEFAULT_DATABRICKS_ENGINE_PROBE_TASK_KEY': ('document_kv_cache.databricks_engine_probe_job', 'DEFAULT_DATABRICKS_ENGINE_PROBE_TASK_KEY'),
    'DatabricksEngineProbeJobConfig': ('document_kv_cache.databricks_engine_probe_job', 'DatabricksEngineProbeJobConfig'),
    'DatabricksEngineProbeMatrixJobConfig': ('document_kv_cache.databricks_engine_probe_job', 'DatabricksEngineProbeMatrixJobConfig'),
    'DatabricksEngineProbeTargetConfig': ('document_kv_cache.databricks_engine_probe_job', 'DatabricksEngineProbeTargetConfig'),
    'DatabricksEngineProbeTargetsFile': ('document_kv_cache.databricks_engine_probe_job', 'DatabricksEngineProbeTargetsFile'),
    'build_databricks_engine_probe_matrix_run_submit_payload': ('document_kv_cache.databricks_engine_probe_job', 'build_databricks_engine_probe_matrix_run_submit_payload'),
    'build_databricks_engine_probe_run_submit_payload': ('document_kv_cache.databricks_engine_probe_job', 'build_databricks_engine_probe_run_submit_payload'),
    'read_databricks_engine_probe_targets_file_json': ('document_kv_cache.databricks_engine_probe_job', 'read_databricks_engine_probe_targets_file_json'),
    'read_databricks_engine_probe_targets_json': ('document_kv_cache.databricks_engine_probe_job', 'read_databricks_engine_probe_targets_json'),
    'run_engine_probe_task': ('document_kv_cache.databricks_engine_probe_job', 'run_engine_probe_task'),
    'write_databricks_engine_probe_matrix_run_submit_json': ('document_kv_cache.databricks_engine_probe_job', 'write_databricks_engine_probe_matrix_run_submit_json'),
    'write_databricks_engine_probe_run_submit_json': ('document_kv_cache.databricks_engine_probe_job', 'write_databricks_engine_probe_run_submit_json'),
    'write_databricks_engine_probe_runner_script': ('document_kv_cache.databricks_engine_probe_job', 'write_databricks_engine_probe_runner_script'),
    'DEDICATED_DATABRICKS_DATA_SECURITY_MODE': ('document_kv_cache.databricks_job', 'DEDICATED_DATABRICKS_DATA_SECURITY_MODE'),
    'DEFAULT_AWS_SINGLE_NODE_GPU_NODE_TYPE': ('document_kv_cache.databricks_job', 'DEFAULT_AWS_SINGLE_NODE_GPU_NODE_TYPE'),
    'DEFAULT_AWS_G5_NODE_TYPE': ('document_kv_cache.databricks_job', 'DEFAULT_AWS_G5_NODE_TYPE'),
    'DEFAULT_DATABRICKS_DATA_SECURITY_MODE': ('document_kv_cache.databricks_job', 'DEFAULT_DATABRICKS_DATA_SECURITY_MODE'),
    'DEFAULT_DATABRICKS_PURPOSE': ('document_kv_cache.databricks_job', 'DEFAULT_DATABRICKS_PURPOSE'),
    'DEFAULT_DATABRICKS_RUN_NAME': ('document_kv_cache.databricks_job', 'DEFAULT_DATABRICKS_RUN_NAME'),
    'DEFAULT_DATABRICKS_SPARK_VERSION': ('document_kv_cache.databricks_job', 'DEFAULT_DATABRICKS_SPARK_VERSION'),
    'DEFAULT_DATABRICKS_TASK_KEY': ('document_kv_cache.databricks_job', 'DEFAULT_DATABRICKS_TASK_KEY'),
    'DatabricksSingleNodeGPUClusterConfig': ('document_kv_cache.databricks_job', 'DatabricksSingleNodeGPUClusterConfig'),
    'DatabricksBenchmarkJobConfig': ('document_kv_cache.databricks_job', 'DatabricksBenchmarkJobConfig'),
    'DatabricksSingleNodeG5ClusterConfig': ('document_kv_cache.databricks_job', 'DatabricksSingleNodeG5ClusterConfig'),
    'RESERVED_SINGLE_NODE_GPU_TAG_KEYS': ('document_kv_cache.databricks_job', 'RESERVED_SINGLE_NODE_GPU_TAG_KEYS'),
    'SINGLE_USER_DATABRICKS_DATA_SECURITY_MODES': ('document_kv_cache.databricks_job', 'SINGLE_USER_DATABRICKS_DATA_SECURITY_MODES'),
    'build_databricks_run_submit_payload': ('document_kv_cache.databricks_job', 'build_databricks_run_submit_payload'),
    'build_single_node_gpu_cluster': ('document_kv_cache.databricks_job', 'build_single_node_gpu_cluster'),
    'build_single_node_g5_cluster': ('document_kv_cache.databricks_job', 'build_single_node_g5_cluster'),
    'validate_aws_single_node_gpu_type': ('document_kv_cache.databricks_job', 'validate_aws_single_node_gpu_type'),
    'validate_aws_g5_node_type': ('document_kv_cache.databricks_job', 'validate_aws_g5_node_type'),
    'write_databricks_run_submit_json': ('document_kv_cache.databricks_job', 'write_databricks_run_submit_json'),
    'write_databricks_runner_script': ('document_kv_cache.databricks_job', 'write_databricks_runner_script'),
    'DATABRICKS_AUTH_CHECK_RECORD_TYPE': ('document_kv_cache.databricks_runs', 'DATABRICKS_AUTH_CHECK_RECORD_TYPE'),
    'DATABRICKS_DBFS_PUT_MAX_CONTENT_BYTES': ('document_kv_cache.databricks_runs', 'DATABRICKS_DBFS_PUT_MAX_CONTENT_BYTES'),
    'DATABRICKS_PROFILE_AUTH_MODES': ('document_kv_cache.databricks_runs', 'DATABRICKS_PROFILE_AUTH_MODES'),
    'DATABRICKS_RUN_STATUS_RECORD_TYPE': ('document_kv_cache.databricks_runs', 'DATABRICKS_RUN_STATUS_RECORD_TYPE'),
    'DATABRICKS_RUN_SUBMIT_PAYLOAD_RECORD_TYPE': ('document_kv_cache.databricks_runs', 'DATABRICKS_RUN_SUBMIT_PAYLOAD_RECORD_TYPE'),
    'DEFAULT_DATABRICKS_CONFIG_FILE': ('document_kv_cache.databricks_runs', 'DEFAULT_DATABRICKS_CONFIG_FILE'),
    'DEFAULT_DATABRICKS_HOST_ENV': ('document_kv_cache.databricks_runs', 'DEFAULT_DATABRICKS_HOST_ENV'),
    'DEFAULT_DATABRICKS_TIMEOUT_SECONDS': ('document_kv_cache.databricks_runs', 'DEFAULT_DATABRICKS_TIMEOUT_SECONDS'),
    'DEFAULT_DATABRICKS_TOKEN_ENV': ('document_kv_cache.databricks_runs', 'DEFAULT_DATABRICKS_TOKEN_ENV'),
    'DatabricksWorkspaceConfig': ('document_kv_cache.databricks_runs', 'DatabricksWorkspaceConfig'),
    'databricks_run_status_record': ('document_kv_cache.databricks_runs', 'databricks_run_status_record'),
    'databricks_run_status_sidecar_issues': ('document_kv_cache.databricks_runs', 'databricks_run_status_sidecar_issues'),
    'check_databricks_auth': ('document_kv_cache.databricks_runs', 'check_databricks_auth'),
    'databricks_workspace_config_from_env': ('document_kv_cache.databricks_runs', 'databricks_workspace_config_from_env'),
    'databricks_workspace_config_from_profile': ('document_kv_cache.databricks_runs', 'databricks_workspace_config_from_profile'),
    'databricks_workspace_config_from_sdk_profile': ('document_kv_cache.databricks_runs', 'databricks_workspace_config_from_sdk_profile'),
    'get_databricks_run': ('document_kv_cache.databricks_runs', 'get_databricks_run'),
    'plan_databricks_stage_and_submit': ('document_kv_cache.databricks_runs', 'plan_databricks_stage_and_submit'),
    'put_databricks_dbfs_file': ('document_kv_cache.databricks_runs', 'put_databricks_dbfs_file'),
    'read_databricks_run_submit_payload': ('document_kv_cache.databricks_runs', 'read_databricks_run_submit_payload'),
    'stage_and_submit_databricks_run': ('document_kv_cache.databricks_runs', 'stage_and_submit_databricks_run'),
    'submit_databricks_run': ('document_kv_cache.databricks_runs', 'submit_databricks_run'),
    'summarize_databricks_run': ('document_kv_cache.databricks_runs', 'summarize_databricks_run'),
    'summarize_databricks_run_submit_payload': ('document_kv_cache.databricks_runs', 'summarize_databricks_run_submit_payload'),
    'validate_databricks_run_status_sidecar': ('document_kv_cache.databricks_runs', 'validate_databricks_run_status_sidecar'),
    'write_databricks_run_response_json': ('document_kv_cache.databricks_runs', 'write_databricks_run_response_json'),
    'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_PURPOSE': ('document_kv_cache.databricks_storage_benchmark_job', 'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_PURPOSE'),
    'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_RUN_NAME': ('document_kv_cache.databricks_storage_benchmark_job', 'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_RUN_NAME'),
    'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_TASK_KEY': ('document_kv_cache.databricks_storage_benchmark_job', 'DEFAULT_DATABRICKS_STORAGE_BENCHMARK_TASK_KEY'),
    'DatabricksStorageBenchmarkJobConfig': ('document_kv_cache.databricks_storage_benchmark_job', 'DatabricksStorageBenchmarkJobConfig'),
    'build_databricks_storage_benchmark_run_submit_payload': ('document_kv_cache.databricks_storage_benchmark_job', 'build_databricks_storage_benchmark_run_submit_payload'),
    'write_databricks_storage_benchmark_run_submit_json': ('document_kv_cache.databricks_storage_benchmark_job', 'write_databricks_storage_benchmark_run_submit_json'),
    'write_databricks_storage_benchmark_runner_script': ('document_kv_cache.databricks_storage_benchmark_job', 'write_databricks_storage_benchmark_runner_script'),
    'DEFAULT_DATABRICKS_SGLANG_SMOKE_PURPOSE': ('document_kv_cache.databricks_sglang_smoke_job', 'DEFAULT_DATABRICKS_SGLANG_SMOKE_PURPOSE'),
    'DEFAULT_DATABRICKS_SGLANG_SMOKE_RUN_NAME': ('document_kv_cache.databricks_sglang_smoke_job', 'DEFAULT_DATABRICKS_SGLANG_SMOKE_RUN_NAME'),
    'DEFAULT_DATABRICKS_SGLANG_SMOKE_TASK_KEY': ('document_kv_cache.databricks_sglang_smoke_job', 'DEFAULT_DATABRICKS_SGLANG_SMOKE_TASK_KEY'),
    'DatabricksSGLangSmokeJobConfig': ('document_kv_cache.databricks_sglang_smoke_job', 'DatabricksSGLangSmokeJobConfig'),
    'build_databricks_sglang_smoke_run_submit_payload': ('document_kv_cache.databricks_sglang_smoke_job', 'build_databricks_sglang_smoke_run_submit_payload'),
    'write_databricks_sglang_smoke_run_submit_json': ('document_kv_cache.databricks_sglang_smoke_job', 'write_databricks_sglang_smoke_run_submit_json'),
    'write_databricks_sglang_smoke_runner_script': ('document_kv_cache.databricks_sglang_smoke_job', 'write_databricks_sglang_smoke_runner_script'),
    'DEFAULT_DATABRICKS_VLLM_SMOKE_PURPOSE': ('document_kv_cache.databricks_vllm_smoke_job', 'DEFAULT_DATABRICKS_VLLM_SMOKE_PURPOSE'),
    'DEFAULT_DATABRICKS_VLLM_SMOKE_RUN_NAME': ('document_kv_cache.databricks_vllm_smoke_job', 'DEFAULT_DATABRICKS_VLLM_SMOKE_RUN_NAME'),
    'DEFAULT_DATABRICKS_VLLM_SMOKE_TASK_KEY': ('document_kv_cache.databricks_vllm_smoke_job', 'DEFAULT_DATABRICKS_VLLM_SMOKE_TASK_KEY'),
    'DatabricksVLLMSmokeJobConfig': ('document_kv_cache.databricks_vllm_smoke_job', 'DatabricksVLLMSmokeJobConfig'),
    'build_databricks_vllm_smoke_run_submit_payload': ('document_kv_cache.databricks_vllm_smoke_job', 'build_databricks_vllm_smoke_run_submit_payload'),
    'write_databricks_vllm_smoke_run_submit_json': ('document_kv_cache.databricks_vllm_smoke_job', 'write_databricks_vllm_smoke_run_submit_json'),
    'write_databricks_vllm_smoke_runner_script': ('document_kv_cache.databricks_vllm_smoke_job', 'write_databricks_vllm_smoke_runner_script'),
    'DEFAULT_NIAH_QUERY': ('document_kv_cache.dataset_prep', 'DEFAULT_NIAH_QUERY'),
    'build_niah_record': ('document_kv_cache.dataset_prep', 'build_niah_record'),
    'convert_v1_jsonl': ('document_kv_cache.dataset_prep', 'convert_v1_jsonl'),
    'normalize_v1_record': ('document_kv_cache.dataset_prep', 'normalize_v1_record'),
    'write_v1_jsonl': ('document_kv_cache.dataset_prep', 'write_v1_jsonl'),
    'EngineReadyRequest': ('document_kv_cache.engine', 'EngineReadyRequest'),
    'ServingEngineConnector': ('document_kv_cache.engine', 'ServingEngineConnector'),
    'build_engine_ready_request': ('document_kv_cache.engine', 'build_engine_ready_request'),
    'build_handle_from_materialized': ('document_kv_cache.engine', 'build_handle_from_materialized'),
    'ENGINE_KV_CONNECTOR_ACTIONS_RECORD_TYPE': ('document_kv_cache.engine_adapters', 'ENGINE_KV_CONNECTOR_ACTIONS_RECORD_TYPE'),
    'ENGINE_KV_CONNECTOR_ACTIONS_SCHEMA_VERSION': ('document_kv_cache.engine_adapters', 'ENGINE_KV_CONNECTOR_ACTIONS_SCHEMA_VERSION'),
    'ENGINE_KV_CONNECTOR_PROBE_RECORD_TYPE': ('document_kv_cache.engine_adapters', 'ENGINE_KV_CONNECTOR_PROBE_RECORD_TYPE'),
    'ENGINE_KV_CONNECTOR_PROBE_SCHEMA_VERSION': ('document_kv_cache.engine_adapters', 'ENGINE_KV_CONNECTOR_PROBE_SCHEMA_VERSION'),
    'EngineAdapterRequest': ('document_kv_cache.engine_adapters', 'EngineAdapterRequest'),
    'EngineAdapterSpec': ('document_kv_cache.engine_adapters', 'EngineAdapterSpec'),
    'EngineKVBindAction': ('document_kv_cache.engine_adapters', 'EngineKVBindAction'),
    'EngineKVBlockManagerProbe': ('document_kv_cache.engine_adapters', 'EngineKVBlockManagerProbe'),
    'EngineKVConnectorActions': ('document_kv_cache.engine_adapters', 'EngineKVConnectorActions'),
    'EngineKVConnectorProbeResult': ('document_kv_cache.engine_adapters', 'EngineKVConnectorProbeResult'),
    'EngineKVInjectionPlan': ('document_kv_cache.engine_adapters', 'EngineKVInjectionPlan'),
    'EngineKVReleaseAction': ('document_kv_cache.engine_adapters', 'EngineKVReleaseAction'),
    'EngineKVReservationAction': ('document_kv_cache.engine_adapters', 'EngineKVReservationAction'),
    'EngineKVSegmentBinding': ('document_kv_cache.engine_adapters', 'EngineKVSegmentBinding'),
    'EngineKVSegmentCopyAction': ('document_kv_cache.engine_adapters', 'EngineKVSegmentCopyAction'),
    'PayloadMode': ('document_kv_cache.engine_adapters', 'PayloadMode'),
    'ServingBackend': ('document_kv_cache.engine_adapters', 'ServingBackend'),
    'build_engine_adapter_request': ('document_kv_cache.engine_adapters', 'build_engine_adapter_request'),
    'build_engine_kv_connector_actions': ('document_kv_cache.engine_adapters', 'build_engine_kv_connector_actions'),
    'build_engine_kv_injection_plan': ('document_kv_cache.engine_adapters', 'build_engine_kv_injection_plan'),
    'engine_adapter_request_to_record': ('document_kv_cache.engine_adapters', 'engine_adapter_request_to_record'),
    'engine_kv_connector_actions_from_record': ('document_kv_cache.engine_adapters', 'engine_kv_connector_actions_from_record'),
    'engine_kv_connector_actions_to_record': ('document_kv_cache.engine_adapters', 'engine_kv_connector_actions_to_record'),
    'engine_kv_connector_probe_result_to_record': ('document_kv_cache.engine_adapters', 'engine_kv_connector_probe_result_to_record'),
    'payload_mode_for': ('document_kv_cache.engine_adapters', 'payload_mode_for'),
    'probe_engine_kv_connector_actions': ('document_kv_cache.engine_adapters', 'probe_engine_kv_connector_actions'),
    'read_engine_adapter_request_json': ('document_kv_cache.engine_adapters', 'read_engine_adapter_request_json'),
    'sglang_adapter_spec': ('document_kv_cache.engine_adapters', 'sglang_adapter_spec'),
    'split_engine_adapter_payload': ('document_kv_cache.engine_adapters', 'split_engine_adapter_payload'),
    'validate_engine_adapter_request_record': ('document_kv_cache.engine_adapters', 'validate_engine_adapter_request_record'),
    'validate_engine_kv_connector_actions': ('document_kv_cache.engine_adapters', 'validate_engine_kv_connector_actions'),
    'validate_engine_kv_connector_actions_record': ('document_kv_cache.engine_adapters', 'validate_engine_kv_connector_actions_record'),
    'validate_engine_kv_connector_probe_record': ('document_kv_cache.engine_adapters', 'validate_engine_kv_connector_probe_record'),
    'view_engine_adapter_payload': ('document_kv_cache.engine_adapters', 'view_engine_adapter_payload'),
    'vllm_adapter_spec': ('document_kv_cache.engine_adapters', 'vllm_adapter_spec'),
    'write_engine_adapter_request_json': ('document_kv_cache.engine_adapters', 'write_engine_adapter_request_json'),
    'DEFAULT_ENGINE_LAUNCH_CONFIG_KV_INJECTION_METHOD': ('document_kv_cache.engine_launch_config', 'DEFAULT_ENGINE_LAUNCH_CONFIG_KV_INJECTION_METHOD'),
    'DEFAULT_ENGINE_LAUNCH_CONFIG_SCHEMA_VERSION': ('document_kv_cache.engine_launch_config', 'DEFAULT_ENGINE_LAUNCH_CONFIG_SCHEMA_VERSION'),
    'DEFAULT_SGLANG_DOCUMENT_KV_MODULE_PATH': ('document_kv_cache.engine_launch_config', 'DEFAULT_SGLANG_DOCUMENT_KV_MODULE_PATH'),
    'DEFAULT_SGLANG_DOCUMENT_KV_PROVIDER_FACTORY': ('document_kv_cache.engine_launch_config', 'DEFAULT_SGLANG_DOCUMENT_KV_PROVIDER_FACTORY'),
    'DEFAULT_SGLANG_ENGINE_LAUNCH_CONFIG_RECORD_TYPE': ('document_kv_cache.engine_launch_config', 'DEFAULT_SGLANG_ENGINE_LAUNCH_CONFIG_RECORD_TYPE'),
    'DEFAULT_VLLM_DOCUMENT_KV_MODULE_PATH': ('document_kv_cache.engine_launch_config', 'DEFAULT_VLLM_DOCUMENT_KV_MODULE_PATH'),
    'DEFAULT_VLLM_ENGINE_LAUNCH_CONFIG_RECORD_TYPE': ('document_kv_cache.engine_launch_config', 'DEFAULT_VLLM_ENGINE_LAUNCH_CONFIG_RECORD_TYPE'),
    'ENGINE_LAUNCH_CONFIG_EVIDENCE_RECORD_TYPE': ('document_kv_cache.engine_launch_config', 'ENGINE_LAUNCH_CONFIG_EVIDENCE_RECORD_TYPE'),
    'ENGINE_LAUNCH_CONFIG_EVIDENCE_SCHEMA_VERSION': ('document_kv_cache.engine_launch_config', 'ENGINE_LAUNCH_CONFIG_EVIDENCE_SCHEMA_VERSION'),
    'REQUIRED_ENGINE_LAUNCH_CONFIG_BACKENDS': ('document_kv_cache.engine_launch_config', 'REQUIRED_ENGINE_LAUNCH_CONFIG_BACKENDS'),
    'EngineLaunchConfigEvidence': ('document_kv_cache.engine_launch_config', 'EngineLaunchConfigEvidence'),
    'build_sglang_launch_config': ('document_kv_cache.engine_launch_config', 'build_sglang_launch_config'),
    'build_vllm_launch_config': ('document_kv_cache.engine_launch_config', 'build_vllm_launch_config'),
    'engine_launch_config_evidence_to_record': ('document_kv_cache.engine_launch_config', 'engine_launch_config_evidence_to_record'),
    'engine_launch_config_record_issues': ('document_kv_cache.engine_launch_config', 'engine_launch_config_record_issues'),
    'evaluate_engine_launch_config_evidence': ('document_kv_cache.engine_launch_config', 'evaluate_engine_launch_config_evidence'),
    'read_engine_launch_config_json': ('document_kv_cache.engine_launch_config', 'read_engine_launch_config_json'),
    'validate_engine_launch_config_record': ('document_kv_cache.engine_launch_config', 'validate_engine_launch_config_record'),
    'write_engine_launch_config_json': ('document_kv_cache.engine_launch_config', 'write_engine_launch_config_json'),
    'write_engine_launch_config_evidence_json': ('document_kv_cache.engine_launch_config', 'write_engine_launch_config_evidence_json'),
    'ENGINE_KV_PROBE_METADATA_EXPECTED_BACKEND': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_EXPECTED_BACKEND'),
    'ENGINE_KV_PROBE_METADATA_HANDOFF_JSON': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_HANDOFF_JSON'),
    'ENGINE_KV_PROBE_METADATA_PAYLOAD_URI': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_PAYLOAD_URI'),
    'ENGINE_KV_PROBE_METADATA_PROBE_FACTORY': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_PROBE_FACTORY'),
    'ENGINE_KV_PROBE_METADATA_SERVING_ENGINE_PACKAGE': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_SERVING_ENGINE_PACKAGE'),
    'ENGINE_KV_PROBE_METADATA_SERVING_ENGINE_VERSION': ('document_kv_cache.engine_probe', 'ENGINE_KV_PROBE_METADATA_SERVING_ENGINE_VERSION'),
    'EngineKVProbeConfig': ('document_kv_cache.engine_probe', 'EngineKVProbeConfig'),
    'EngineKVProbeFactory': ('document_kv_cache.engine_probe', 'EngineKVProbeFactory'),
    'EngineKVProbeFactoryContext': ('document_kv_cache.engine_probe', 'EngineKVProbeFactoryContext'),
    'EngineKVProbeFactoryResult': ('document_kv_cache.engine_probe', 'EngineKVProbeFactoryResult'),
    'load_engine_kv_probe_factory': ('document_kv_cache.engine_probe', 'load_engine_kv_probe_factory'),
    'read_engine_adapter_payload': ('document_kv_cache.engine_probe', 'read_engine_adapter_payload'),
    'run_engine_kv_connector_probe': ('document_kv_cache.engine_probe', 'run_engine_kv_connector_probe'),
    'write_engine_adapter_handoff_bundle': ('document_kv_cache.engine_probe', 'write_engine_adapter_handoff_bundle'),
    'write_engine_adapter_payload': ('document_kv_cache.engine_probe', 'write_engine_adapter_payload'),
    'write_engine_kv_connector_actions_record_json': ('document_kv_cache.engine_probe', 'write_engine_kv_connector_actions_record_json'),
    'write_engine_kv_connector_probe_result_json': ('document_kv_cache.engine_probe', 'write_engine_kv_connector_probe_result_json'),
    'AttentionMechanism': ('document_kv_cache.engine_protocol', 'AttentionMechanism'),
    'DTYPE_BYTE_WIDTHS': ('document_kv_cache.engine_protocol', 'DTYPE_BYTE_WIDTHS'),
    'KVCacheHandle': ('document_kv_cache.engine_protocol', 'KVCacheHandle'),
    'KVLayout': ('document_kv_cache.engine_protocol', 'KVLayout'),
    'KVSegment': ('document_kv_cache.engine_protocol', 'KVSegment'),
    'KVStorageLayout': ('document_kv_cache.engine_protocol', 'KVStorageLayout'),
    'dtype_byte_width': ('document_kv_cache.engine_protocol', 'dtype_byte_width'),
    'kv_storage_layout_from_value': ('document_kv_cache.engine_protocol', 'kv_storage_layout_from_value'),
    'LIVE_CHECK_SUITE_ID': ('document_kv_cache.live_server', 'LIVE_CHECK_SUITE_ID'),
    'DEFAULT_LIVE_CHECK_PROMPT_FORMAT': ('document_kv_cache.live_server', 'DEFAULT_LIVE_CHECK_PROMPT_FORMAT'),
    'LiveCheckPromptFormat': ('document_kv_cache.live_server', 'LiveCheckPromptFormat'),
    'LiveServerCheckConfig': ('document_kv_cache.live_server', 'LiveServerCheckConfig'),
    'LiveServerCheckResult': ('document_kv_cache.live_server', 'LiveServerCheckResult'),
    'build_live_server_check_request': ('document_kv_cache.live_server', 'build_live_server_check_request'),
    'live_check_kv_transfer_params': ('document_kv_cache.live_server', 'live_check_kv_transfer_params'),
    'run_openai_compatible_live_check': ('document_kv_cache.live_server', 'run_openai_compatible_live_check'),
    'DEFAULT_SGLANG_LIVE_CHECK_PROMPT_FORMAT': ('document_kv_cache.sglang_smoke', 'DEFAULT_SGLANG_LIVE_CHECK_PROMPT_FORMAT'),
    'SGLangSmokeBenchmarkConfig': ('document_kv_cache.sglang_smoke', 'SGLangSmokeBenchmarkConfig'),
    'build_sglang_hicache_provider_probe_record': ('document_kv_cache.sglang_smoke', 'build_sglang_hicache_provider_probe_record'),
    'build_sglang_server_args': ('document_kv_cache.sglang_smoke', 'build_sglang_server_args'),
    'run_sglang_live_smoke': ('document_kv_cache.sglang_smoke', 'run_sglang_live_smoke'),
    'sglang_hicache_config_for_smoke': ('document_kv_cache.sglang_smoke', 'sglang_hicache_config_for_smoke'),
    'sglang_live_kv_transfer_params': ('document_kv_cache.sglang_smoke', 'sglang_live_kv_transfer_params'),
    'InMemoryManifestStore': ('document_kv_cache.manifest', 'InMemoryManifestStore'),
    'ManifestStore': ('document_kv_cache.manifest', 'ManifestStore'),
    'KVMaterializer': ('document_kv_cache.materializer', 'KVMaterializer'),
    'MaterializedKV': ('document_kv_cache.materializer', 'MaterializedKV'),
    'SegmentedMaterializedKV': ('document_kv_cache.materializer', 'SegmentedMaterializedKV'),
    'KVModelProfile': ('document_kv_cache.model_profiles', 'KVModelProfile'),
    'MODEL_PROFILE_RECORD_TYPE': ('document_kv_cache.model_profiles', 'MODEL_PROFILE_RECORD_TYPE'),
    'ModelProfileDefinition': ('document_kv_cache.model_profiles', 'ModelProfileDefinition'),
    'ModelProfileRegistry': ('document_kv_cache.model_profiles', 'ModelProfileRegistry'),
    'QWEN3_4B_BASE_HF_MODEL_ID': ('document_kv_cache.model_profiles', 'QWEN3_4B_BASE_HF_MODEL_ID'),
    'QWEN3_4B_INSTRUCT_HF_MODEL_ID': ('document_kv_cache.model_profiles', 'QWEN3_4B_INSTRUCT_HF_MODEL_ID'),
    'QWEN3_4B_INSTRUCT_PROFILE': ('document_kv_cache.model_profiles', 'QWEN3_4B_INSTRUCT_PROFILE'),
    'builtin_model_profiles': ('document_kv_cache.model_profiles', 'builtin_model_profiles'),
    'default_model_profile_registry': ('document_kv_cache.model_profiles', 'default_model_profile_registry'),
    'get_model_profile': ('document_kv_cache.model_profiles', 'get_model_profile'),
    'layout_for_model': ('document_kv_cache.model_profiles', 'layout_for_model'),
    'model_profile_definition_from_record': ('document_kv_cache.model_profiles', 'model_profile_definition_from_record'),
    'model_profile_definition_to_record': ('document_kv_cache.model_profiles', 'model_profile_definition_to_record'),
    'read_model_profile_definition_json': ('document_kv_cache.model_profiles', 'read_model_profile_definition_json'),
    'write_model_profile_definition_json': ('document_kv_cache.model_profiles', 'write_model_profile_definition_json'),
    'CacheChunkType': ('document_kv_cache.models', 'CacheChunkType'),
    'CacheChunkTypeSet': ('document_kv_cache.models', 'CacheChunkTypeSet'),
    'CacheGenerationMethod': ('document_kv_cache.models', 'CacheGenerationMethod'),
    'ChunkRef': ('document_kv_cache.models', 'ChunkRef'),
    'DEFAULT_STATIC_CHUNK_ID': ('document_kv_cache.models', 'DEFAULT_STATIC_CHUNK_ID'),
    'DOCUMENT_CHUNK_TYPES': ('document_kv_cache.models', 'DOCUMENT_CHUNK_TYPES'),
    'DocumentChunkMap': ('document_kv_cache.models', 'DocumentChunkMap'),
    'DocumentChunkRole': ('document_kv_cache.models', 'DocumentChunkRole'),
    'DocumentChunkType': ('document_kv_cache.models', 'DocumentChunkType'),
    'DocumentKVRequest': ('document_kv_cache.models', 'DocumentKVRequest'),
    'FrozenDocumentChunkMap': ('document_kv_cache.models', 'FrozenDocumentChunkMap'),
    'KVCacheKey': ('document_kv_cache.models', 'KVCacheKey'),
    'MaterializationPlan': ('document_kv_cache.models', 'MaterializationPlan'),
    'PlanSegment': ('document_kv_cache.models', 'PlanSegment'),
    'chunk_type_role': ('document_kv_cache.models', 'chunk_type_role'),
    'chunk_type_sort_order': ('document_kv_cache.models', 'chunk_type_sort_order'),
    'chunk_types_for_request': ('document_kv_cache.models', 'chunk_types_for_request'),
    'NATIVE_PROBE_ADAPTER_CONTRACT': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_ADAPTER_CONTRACT'),
    'NATIVE_PROBE_DELEGATE_CONTRACT_ATTR': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_DELEGATE_CONTRACT_ATTR'),
    'NATIVE_PROBE_DELEGATE_CONTRACT_MODULE_ATTR': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_DELEGATE_CONTRACT_MODULE_ATTR'),
    'NATIVE_PROBE_DELEGATE_RUNTIME_CONTRACT_ATTR': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_DELEGATE_RUNTIME_CONTRACT_ATTR'),
    'NATIVE_PROBE_DELEGATE_RUNTIME_CONTRACT_MODULE_ATTR': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_DELEGATE_RUNTIME_CONTRACT_MODULE_ATTR'),
    'NATIVE_PROBE_FACTORIES_RECORD_TYPE': ('document_kv_cache.native_probe_factories', 'NATIVE_PROBE_FACTORIES_RECORD_TYPE'),
    'NativeProbeFactoryInspection': ('document_kv_cache.native_probe_factories', 'NativeProbeFactoryInspection'),
    'NativeProbeFactoryUnavailable': ('document_kv_cache.native_probe_factories', 'NativeProbeFactoryUnavailable'),
    'SGLANG_NATIVE_PROBE_FACTORY': ('document_kv_cache.native_probe_factories', 'SGLANG_NATIVE_PROBE_FACTORY'),
    'SGLANG_NATIVE_PROBE_DELEGATE_ENV': ('document_kv_cache.native_probe_factories', 'SGLANG_NATIVE_PROBE_DELEGATE_ENV'),
    'VLLM_NATIVE_PROBE_FACTORY': ('document_kv_cache.native_probe_factories', 'VLLM_NATIVE_PROBE_FACTORY'),
    'VLLM_NATIVE_PROBE_DELEGATE_ENV': ('document_kv_cache.native_probe_factories', 'VLLM_NATIVE_PROBE_DELEGATE_ENV'),
    'builtin_native_probe_factories_to_record': ('document_kv_cache.native_probe_factories', 'builtin_native_probe_factories_to_record'),
    'builtin_native_probe_factory_path': ('document_kv_cache.native_probe_factories', 'builtin_native_probe_factory_path'),
    'inspect_builtin_native_probe_factories': ('document_kv_cache.native_probe_factories', 'inspect_builtin_native_probe_factories'),
    'inspect_builtin_native_probe_factory': ('document_kv_cache.native_probe_factories', 'inspect_builtin_native_probe_factory'),
    'native_probe_adapter_contract_to_record': ('document_kv_cache.native_probe_factories', 'native_probe_adapter_contract_to_record'),
    'native_probe_factories_record_issues': ('document_kv_cache.native_probe_factories', 'native_probe_factories_record_issues'),
    'native_probe_factory_inspection_to_record': ('document_kv_cache.native_probe_factories', 'native_probe_factory_inspection_to_record'),
    'native_probe_runtime_contract_to_record': ('document_kv_cache.native_probe_factories', 'native_probe_runtime_contract_to_record'),
    'sglang_native_probe_factory': ('document_kv_cache.native_probe_factories', 'sglang_native_probe_factory'),
    'validate_native_probe_factories_record': ('document_kv_cache.native_probe_factories', 'validate_native_probe_factories_record'),
    'vllm_native_probe_factory': ('document_kv_cache.native_probe_factories', 'vllm_native_probe_factory'),
    'write_builtin_native_probe_factories_record_json': ('document_kv_cache.native_probe_factories', 'write_builtin_native_probe_factories_record_json'),
    'OpenAICompatibleCompletionEngine': ('document_kv_cache.openai_compatible', 'OpenAICompatibleCompletionEngine'),
    'OpenAICompatibleEngineConfig': ('document_kv_cache.openai_compatible', 'OpenAICompatibleEngineConfig'),
    'KVTransferParamsTransport': ('document_kv_cache.openai_compatible', 'KVTransferParamsTransport'),
    'PromptTextMode': ('document_kv_cache.openai_compatible', 'PromptTextMode'),
    'PromptTokenAccounting': ('document_kv_cache.openai_compatible', 'PromptTokenAccounting'),
    'TokenCounter': ('document_kv_cache.openai_compatible', 'TokenCounter'),
    'WhitespaceTokenCounter': ('document_kv_cache.openai_compatible', 'WhitespaceTokenCounter'),
    'CachePlanner': ('document_kv_cache.planner', 'CachePlanner'),
    'CacheRequest': ('document_kv_cache.planner', 'CacheRequest'),
    'GPT55_REVIEW_OUTCOMES': ('document_kv_cache.pr_evidence', 'GPT55_REVIEW_OUTCOMES'),
    'PR_EVIDENCE_RECORD_TYPE': ('document_kv_cache.pr_evidence', 'PR_EVIDENCE_RECORD_TYPE'),
    'PR_EVIDENCE_VALIDATION_RECORD_TYPE': ('document_kv_cache.pr_evidence', 'PR_EVIDENCE_VALIDATION_RECORD_TYPE'),
    'PullRequestEvidence': ('document_kv_cache.pr_evidence', 'PullRequestEvidence'),
    'evaluate_pr_evidence': ('document_kv_cache.pr_evidence', 'evaluate_pr_evidence'),
    'evaluate_pr_evidence_directory': ('document_kv_cache.pr_evidence', 'evaluate_pr_evidence_directory'),
    'evaluate_pr_evidence_file': ('document_kv_cache.pr_evidence', 'evaluate_pr_evidence_file'),
    'evaluate_pr_evidence_record': ('document_kv_cache.pr_evidence', 'evaluate_pr_evidence_record'),
    'pr_evidence_to_record': ('document_kv_cache.pr_evidence', 'pr_evidence_to_record'),
    'pr_evidence_validation_to_record': ('document_kv_cache.pr_evidence', 'pr_evidence_validation_to_record'),
    'write_pr_evidence_json': ('document_kv_cache.pr_evidence', 'write_pr_evidence_json'),
    'RELEASE_BUNDLE_ARTIFACT_ROLES': ('document_kv_cache.release_bundle', 'RELEASE_BUNDLE_ARTIFACT_ROLES'),
    'RELEASE_BUNDLE_MANIFEST_FILENAME': ('document_kv_cache.release_bundle', 'RELEASE_BUNDLE_MANIFEST_FILENAME'),
    'RELEASE_BUNDLE_RECORD_TYPE': ('document_kv_cache.release_bundle', 'RELEASE_BUNDLE_RECORD_TYPE'),
    'ReleaseBundle': ('document_kv_cache.release_bundle', 'ReleaseBundle'),
    'ReleaseBundleArtifact': ('document_kv_cache.release_bundle', 'ReleaseBundleArtifact'),
    'build_release_bundle': ('document_kv_cache.release_bundle', 'build_release_bundle'),
    'release_bundle_to_record': ('document_kv_cache.release_bundle', 'release_bundle_to_record'),
    'write_release_bundle_manifest_json': ('document_kv_cache.release_bundle', 'write_release_bundle_manifest_json'),
    'RELEASE_EVIDENCE_ARTIFACT_ROLES': ('document_kv_cache.release_evidence', 'RELEASE_EVIDENCE_ARTIFACT_ROLES'),
    'RELEASE_EVIDENCE_INPUT_STATUS_RECORD_TYPE': ('document_kv_cache.release_evidence', 'RELEASE_EVIDENCE_INPUT_STATUS_RECORD_TYPE'),
    'RELEASE_EVIDENCE_RECORD_TYPE': ('document_kv_cache.release_evidence', 'RELEASE_EVIDENCE_RECORD_TYPE'),
    'REQUIRED_ENGINE_PROBE_BACKENDS': ('document_kv_cache.release_evidence', 'REQUIRED_ENGINE_PROBE_BACKENDS'),
    'ReleaseEvidence': ('document_kv_cache.release_evidence', 'ReleaseEvidence'),
    'ReleaseEvidenceArtifactSource': ('document_kv_cache.release_evidence', 'ReleaseEvidenceArtifactSource'),
    'ReleaseEvidenceInputFileStatus': ('document_kv_cache.release_evidence', 'ReleaseEvidenceInputFileStatus'),
    'ReleaseEvidenceInputStatus': ('document_kv_cache.release_evidence', 'ReleaseEvidenceInputStatus'),
    'evaluate_release_evidence': ('document_kv_cache.release_evidence', 'evaluate_release_evidence'),
    'evaluate_release_evidence_files': ('document_kv_cache.release_evidence', 'evaluate_release_evidence_files'),
    'inspect_release_evidence_input_files': ('document_kv_cache.release_evidence', 'inspect_release_evidence_input_files'),
    'release_evidence_input_status_to_record': ('document_kv_cache.release_evidence', 'release_evidence_input_status_to_record'),
    'release_evidence_to_record': ('document_kv_cache.release_evidence', 'release_evidence_to_record'),
    'write_release_evidence_input_status_json': ('document_kv_cache.release_evidence', 'write_release_evidence_input_status_json'),
    'write_release_evidence_json': ('document_kv_cache.release_evidence', 'write_release_evidence_json'),
    'DocumentKVService': ('document_kv_cache.service', 'DocumentKVService'),
    'FASTAPI_CONSTRAINT': ('document_kv_cache.serving_env', 'FASTAPI_CONSTRAINT'),
    'HUGGINGFACE_HUB_CONSTRAINT': ('document_kv_cache.serving_env', 'HUGGINGFACE_HUB_CONSTRAINT'),
    'NUMPY_CONSTRAINT': ('document_kv_cache.serving_env', 'NUMPY_CONSTRAINT'),
    'PROMETHEUS_FASTAPI_INSTRUMENTATOR_CONSTRAINT': ('document_kv_cache.serving_env', 'PROMETHEUS_FASTAPI_INSTRUMENTATOR_CONSTRAINT'),
    'SERVING_ENVIRONMENT_PROFILES_RECORD_TYPE': ('document_kv_cache.serving_env', 'SERVING_ENVIRONMENT_PROFILES_RECORD_TYPE'),
    'SGLANG_DEPENDENCY_CONSTRAINTS': ('document_kv_cache.serving_env', 'SGLANG_DEPENDENCY_CONSTRAINTS'),
    'SGLANG_SERVING_ENVIRONMENT_PROFILE': ('document_kv_cache.serving_env', 'SGLANG_SERVING_ENVIRONMENT_PROFILE'),
    'SGLANG_VERSION': ('document_kv_cache.serving_env', 'SGLANG_VERSION'),
    'ServingEnvironmentProfile': ('document_kv_cache.serving_env', 'ServingEnvironmentProfile'),
    'TOKENIZERS_CONSTRAINT': ('document_kv_cache.serving_env', 'TOKENIZERS_CONSTRAINT'),
    'TRANSFORMERS_CONSTRAINT': ('document_kv_cache.serving_env', 'TRANSFORMERS_CONSTRAINT'),
    'VLLM_DEPENDENCY_CONSTRAINTS': ('document_kv_cache.serving_env', 'VLLM_DEPENDENCY_CONSTRAINTS'),
    'VLLM_SERVING_ENVIRONMENT_PROFILE': ('document_kv_cache.serving_env', 'VLLM_SERVING_ENVIRONMENT_PROFILE'),
    'VLLM_VERSION': ('document_kv_cache.serving_env', 'VLLM_VERSION'),
    'serving_environment_profile': ('document_kv_cache.serving_env', 'serving_environment_profile'),
    'serving_environment_profile_to_record': ('document_kv_cache.serving_env', 'serving_environment_profile_to_record'),
    'serving_environment_profiles': ('document_kv_cache.serving_env', 'serving_environment_profiles'),
    'serving_environment_profiles_to_record': ('document_kv_cache.serving_env', 'serving_environment_profiles_to_record'),
    'DiskRangeReader': ('document_kv_cache.storage', 'DiskRangeReader'),
    'MemoryRangeReader': ('document_kv_cache.storage', 'MemoryRangeReader'),
    'RangeBatchReader': ('document_kv_cache.storage', 'RangeBatchReader'),
    'RangeReader': ('document_kv_cache.storage', 'RangeReader'),
    'RoutedRangeReader': ('document_kv_cache.storage', 'RoutedRangeReader'),
    'UnityCatalogVolumeRangeReader': ('document_kv_cache.storage', 'UnityCatalogVolumeRangeReader'),
    'is_real_uc_volume_root': ('document_kv_cache.storage', 'is_real_uc_volume_root'),
    'local_path': ('document_kv_cache.storage', 'local_path'),
    'unity_catalog_volume_path': ('document_kv_cache.storage', 'unity_catalog_volume_path'),
    'RELEASE_STORAGE_BENCHMARK_READERS': ('document_kv_cache.storage_benchmark', 'RELEASE_STORAGE_BENCHMARK_READERS'),
    'STORAGE_BENCHMARK_RECORD_TYPE': ('document_kv_cache.storage_benchmark', 'STORAGE_BENCHMARK_RECORD_TYPE'),
    'SUPPORTED_STORAGE_BENCHMARK_READERS': ('document_kv_cache.storage_benchmark', 'SUPPORTED_STORAGE_BENCHMARK_READERS'),
    'StorageBenchmarkConfig': ('document_kv_cache.storage_benchmark', 'StorageBenchmarkConfig'),
    'StorageBenchmarkEvidence': ('document_kv_cache.storage_benchmark', 'StorageBenchmarkEvidence'),
    'StorageBenchmarkResult': ('document_kv_cache.storage_benchmark', 'StorageBenchmarkResult'),
    'StorageReaderBenchmarkResult': ('document_kv_cache.storage_benchmark', 'StorageReaderBenchmarkResult'),
    'evaluate_release_storage_benchmark_evidence': ('document_kv_cache.storage_benchmark', 'evaluate_release_storage_benchmark_evidence'),
    'evaluate_storage_benchmark_evidence': ('document_kv_cache.storage_benchmark', 'evaluate_storage_benchmark_evidence'),
    'run_storage_benchmark': ('document_kv_cache.storage_benchmark', 'run_storage_benchmark'),
    'storage_benchmark_evidence_to_record': ('document_kv_cache.storage_benchmark', 'storage_benchmark_evidence_to_record'),
    'storage_benchmark_result_to_record': ('document_kv_cache.storage_benchmark', 'storage_benchmark_result_to_record'),
    'write_storage_benchmark_result_json': ('document_kv_cache.storage_benchmark', 'write_storage_benchmark_result_json'),
    'CacheAdapterArtifact': ('document_kv_cache.workflow', 'CacheAdapterArtifact'),
    'CacheBuildConfig': ('document_kv_cache.workflow', 'CacheBuildConfig'),
    'CacheGenerationResult': ('document_kv_cache.workflow', 'CacheGenerationResult'),
    'DocumentKVWorkflow': ('document_kv_cache.workflow', 'DocumentKVWorkflow'),
    'KVChunkGenerator': ('document_kv_cache.workflow', 'KVChunkGenerator'),
    'SourceChunk': ('document_kv_cache.workflow', 'SourceChunk'),
    'SourceDocument': ('document_kv_cache.workflow', 'SourceDocument'),
    'TrainingAdapter': ('document_kv_cache.workflow', 'TrainingAdapter'),
    'TrainingArtifacts': ('document_kv_cache.workflow', 'TrainingArtifacts'),
}

__all__ = list(_DOCUMENT_ROOT_EXPORTS)


def __getattr__(name: str) -> Any:
    if name in _PUBLIC_SUBMODULES:
        module = import_module(f"{__name__}.{name}")
        globals()[name] = module
        return module
    if name in _DOCUMENT_ROOT_EXPORTS:
        module_name, symbol_name = _DOCUMENT_ROOT_EXPORTS[name]
        value = getattr(import_module(module_name), symbol_name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__, *_PUBLIC_SUBMODULES})
